---
apiVersion: v1
kind: Namespace
metadata:
  name: mapreduce
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: server
  namespace: mapreduce
spec:
  replicas: 1 
  selector:
    matchLabels:
      system: server
      run: server
  template:
    metadata:
      labels:
        system: server
        run: server
    spec:
      containers:
      - name: sv
        image: haroldmei/mapreduce:latest
        command: ["/bin/sv.bin"]
        args: ["/data", "3"]
        ports:
        - containerPort: 8080
        env:
        - name: GOOGLE_APPLICATION_CREDENTIALS
          value: /test-pd/adc.json
        - name: GCLOUD_PROJECT
          value: gcp-wow-rwds-ai-mlchapter-dev
          
        volumeMounts:
        - mountPath: /test-pd
          name: test-volume
      volumes:
      - name: test-volume
        gcePersistentDisk:
          pdName: hm-data-disk
          fsType: ext4
          readOnly: true
---
apiVersion: v1
kind: Service
metadata:
  name: server
  namespace: mapreduce
  labels:
    run: server
spec:
  ports:
  - port: 8080
    protocol: TCP
  selector:
    run: server
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: client
  namespace: mapreduce
spec:
  replicas: 3 
  selector:
    matchLabels:
      system: ReplicaOne
  template:
    metadata:
      labels:
        system: ReplicaOne
    spec:
      containers:
      - name: cl
        image: haroldmei/mapreduce:latest
        command: ["/bin/sh","-c", "sleep 30s && /bin/cl.bin"]
        env:
        - name: GOOGLE_APPLICATION_CREDENTIALS
          value: /test-pd/adc.json
        - name: GCLOUD_PROJECT
          value: gcp-wow-rwds-ai-mlchapter-dev

        volumeMounts:
        - mountPath: /test-pd
          name: test-volume
      volumes:
      - name: test-volume
        gcePersistentDisk:
          pdName: hm-data-disk
          fsType: ext4
          readOnly: true

