//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by Resource.rc
//
#define ID_LOAD                         3
#define IDD_SYSSETTING                  101
#define IDD_BASICDISKSCAN               102
#define IDD_DIALOG_AUTH                 104
#define IDD_DETECTPROGRESS              105
#define IDD_USERDEFINED                 106
#define IDB_THREESTATE                  109
#define IDD_DIALOG3                     110
#define DISKFULLSCAN_IDCANCEL           1000
#define DISKFULLSCAN_IDSTART            1001
#define IDC_FULLSCAN_PROGRESS1          1002
#define IDC_DISKDEEPSCANLIST            1003
#define IDD_PERSONLIST                  1004
#define IDD_REPORT                      1005
#define IDD_REGLOAD                     1006
#define IDC_FULLSCANKEYWORDS            1009
#define IDC_FULL_EDIT1                  1010
#define IDC_FULLSCANEDIT2               1012
#define IDC_BROWSE                      1013
#define IDC_EDIT_FILEPATH               1014
#define IDC_EDIT_KEYWORDS               1015
#define IDC_EDIT_NAME                   1016
#define IDC_EDIT_DEPART                 1017
#define IDC_EDIT_IPADDR                 1018
#define IDC_EDIT_HOSTNAME               1019
#define IDC_RP_BROWSE                   1020
#define IDC_PRLIST                      1021
#define IDC_REPORTDATE                  1022
#define IDC_DATAGRID                    1025
#define IDC_SCORE_DEFAULT               1026
#define IDC_SCORE_SAVE                  1027
#define IDC_BASIC_SEARCH                1028
#define IDC_BASIC_CANCEL                1029
#define IDC_BASIC_LIST                  1030
#define IDC_BASIC_KEYWORDS              1031
#define IDC_BASIC_LEFTTREE              1032
#define IDC_BASIC_SRESULT               1033
#define IDC_DEEP_LEFTTREE               1034
#define IDC_DEEP_LIST                   1035
#define IDC_DEEP_PROGRESS               1036
#define IDC_DEEP_START                  1037
#define IDC_DEEP_CANCEL                 1038
#define IDC_FULL_LEFTTREE               1039
#define IDC_FULL_LIST                   1040
#define IDC_FULL_PRESECTOR              1041
#define IDC_FULL_NEXTSECTOR             1042
#define IDC_EDIT_SERVER                 1044
#define IDOK_AUTH                       1045
#define IDC_RADIO_PC                    1046
#define IDC_RADIO_NETWORK               1047
#define IDC_CURITEMTEXT                 1048
#define IDC_USERDEFINECOMBO             1049
#define IDC_USERDEFINESTATIC            1050
#define IDC_EDIT_CONTENT                1051
#define IDC_USERDEFINETIP               1052
#define IDC_TAB1                        1053
#define IDC_EDIT_TEST                   1054
#define IDC_CHECKURL                    1055
#define IDC_BASIC_SRESULTTXT            1056
#define IDC_USERS                       1057
#define IDC_SAVELOG                     1058
#define IDC_SCORE_CALC2                 1100
#define IDC_SCORE_DISPLAY               1101
#define IDC_FULL_CURSECTEXT             1112
#define IDC_FULL_CURSECTEXT2            1113
#define IDC_FULL_CURSECTEXT3            1114
#define IDC_PROGRESSBAR                 1115
#define IDC_REG_BROWSE                  1116
#define IDC_SCORE_CALC                  1117
#define IDC_BUTTON4                     1118
#define IDC_EDIT_STARTTIME              1119
#define IDC_FULL_EDIT2                  1120
#define IDC_FULL_KEYWORDS               1121
#define IDC_FULLSCANEDIT1               1122
#define IDD_TAB_SECTOR                  1123
#define IDC_FULL_CANCEL                 1124
#define IDC_FULL_START                  1125
#define IDC_BUTTON3                     1126
#define IDC_SCORE_CLOSE                 1127
#define IDC_FULL_PROGRESS               1128
#define IDC_CUSTOM2                     1129
#define IDC_PRSAVEPATH                  4003
#define IDC_EDIT_PASSWORD               4003
#define IDC_EDIT_USER                   4004
#define IDC_EDIT_SECRET                 4005
#define ID__40002                       40002
#define ID_VIEW_                        40004
#define ID_40005                        40005
#define ID_40006                        40006
#define ID_40008                        40008
#define ID_NODE_ADD                     40014
#define ID_NODE_DELETE                  40015
#define ID_NODE_MODIFY                  40016
#define ID_SCORE_SETTINGS               40019
#define ID_NODE_REFRESH                 40021
#define ID_Menu                         40022
#define ID_SECURITY_BASIC               40029
#define ID_SECURITY_FULL                40030
#define ID_SECURITY_DEEP                40031
#define ID_TEST_TEST1                   40032
#define ID_REFRESH_MD5                  40034
#define ID_START                        40035
#define ID_SYS_SETTING                  40036
#define ID_EXPORT                       40038
#define ID_Menu40039                    40039
#define IDC_LOCATION                    40040
#define ID_STOP                         40041
#define ID_AUTH_SETTING                 40042
#define ID_NODE_USERDEFINED             40044
#define ID_SAVE_CFG                     40046
#define ID_REGLOAD                      40048
#define ID_SECURITY_MGR                 40051

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NO_MFC                     1
#define _APS_NEXT_RESOURCE_VALUE        111
#define _APS_NEXT_COMMAND_VALUE         40053
#define _APS_NEXT_CONTROL_VALUE         1059
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
